{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_allure.TestAllure object at 0x7f868ce67780>\n\n    @allure.story(\"登录异常\")\n    @allure.severity(\"critical\")\n    def test_login2(self):\n        print(\"login2\")\n>       assert 0\nE       assert 0\n\nscripts/test_allure.py:21: AssertionError"}, "start": 1591240175042, "stop": 1591240175042, "uuid": "262f0ed7-6f79-4434-9a79-7c2bd53423f0", "historyId": "603feb5764fe7bc95146b99f37b19f08", "testCaseId": "3c189df9542b5d6f90411feb86c30516", "fullName": "scripts.test_allure.TestAllure#test_login2", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "登录异常"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "localhost.localdomain"}, {"name": "thread", "value": "4715-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_allure"}]}